#!/bin/bash
PLUGINS="$HOME/.local/share/nvim/site/pack/packer"
nvim_plugins_backup=$(for f in $PLUGINS/{start,opt}/*; do pushd $f >/dev/null;
commit=$(git log --oneline | head -n1 | cut -d' ' -f1); echo "$(basename $f): $commit"; popd >/dev/null; done)
echo "$nvim_plugins_backup" > ~/.cache/nvim_plugins_backup
echo "$(nvim --version | head -n1)" >> ~/.cache/nvim_plugins_backup

