#!/bin/sh
# $1 pattern (regex)
# $2 man page name, default= everything
pattern=$1
default=.
[ -z "$1" ] && exit
[ -n "$2" ] && default="$2"

manpage=$(man -w | tr ':' '\n' | xargs -n1 -I{} fd "$default" {} -x rg "$pattern" . 2>/dev/null | fzf --preview='echo {} | cut -d: -f1 | read -r file; man $file' | cut -d':' -f1)
man "$manpage"
