#!/bin/sh

cd "$PROGRAMS"
sudo -u "$1" git clone https://github.com/Akuseru1/CopyQ-Vi-Colemak-bindings
cd "CopyQ-Vi-Colemak-bindings"
git remote add upstream https://github.com/hluk/CopyQ
# cmake and git have to be installed
eopkg it -y cmake

eopkg it -y \
    qt5-script-devel \
    qt5-tools-devel \
    qt5-svg-devel \
    qt5-x11extras-devel \
    libxtst-devel

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .
make
make install
