#!/bin/sh

cd "$PROGRAMS"
#Clone the repo
sudo -u "$1" git clone --depth=1 https://github.com/sdushantha/fontpreview

# Change your current directory to fontpreview
cd fontpreview

# Install it
make install
