#!/bin/sh

cd "$PROGRAMS"
sudo -u "$SUDO_USER" git clone --depth=1 https://github.com/neovim/neovim
cd neovim
# make CMAKE_BUILD_TYPE=RelWithDebInfo
make  CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$PROGRAMS/prefix-installs/neovim"
make CMAKE_BUILD_TYPE=Release install

sudo -u "$SUDO_USER" python3 -m pip install --user --upgrade pynvim neovim-remote
sudo -u "$SUDO_USER" python2 -m pip install --user --upgrade pynvim
npm install -g neovim

mkdir -p "$HOME/.config/nvim/log"
touch "$HOME/.config/nvim/log/log"

ln -s $(which nvim) /usr/bin/nvim
ln -s $(which nvim) /usr/bin/vim
