#!/bin/sh

#pdfgrep dependencies, download the tar https://pdfgrep.org/download.html
sudo eopkg install -y libgcrypt-devel poppler-devel

cd "$PROGRAMS"
sudo -u "$1" git clone https://gitlab.com/pdfgrep/pdfgrep.git
cd "pdfgrep"
./configure
sudo make
sudo make install
