#!/bin/sh

cd "$PROGRAMS" || exit
version="proxychains-4.4.0"
sudo -u "$SUDO_USER" wget "https://github.com/haad/proxychains/archive/refs/tags/$version.tar.gz"
sudo -u "$SUDO_USER" tar vvxf "$version.tar.gz"
rm "$version.tar.gz"
cd "proxychains-$version" || exit
./configure --prefix=$PROGRAMS/prefix-installs/proxychains
# to supress the gcc wno-stringop-truncation, in this version
# see https://github.com/NixOS/nixpkgs/pull/112994/commits/7eaa45b2b06d5abce71c953d1f526e4630d45d82
sed -i 's/-Werror/-Werror -Wno-stringop-truncation/g' Makefile
make
make install
