#!/bin/sh

if [ ! -e "$PROGRAMS/rust/cargo" ]; then
    $OS/Build-Programs/rust
fi

# --locked because of bug in the ripgrep_all AT THE MOMENT OF CREATION
sudo -u $SUDO_USER -E PATH="$PATH" "$CARGO_HOME/bin/cargo" install --locked ripgrep_all
