#!/bin/sh

#install teamviewer
eopkg install -y qt5-quickcontrols

cd "$PROGRAMS"
sudo -u "$1" wget https://download.teamviewer.com/download/linux/teamviewer_amd64.tar.xz
sudo -u "$1" tar kvvxf teamviewer_amd64.tar.xz
rm teamviewer_amd64.tar.xz
