#!/bin/bash

# dont move the dotfiles from its cloned location

#args: $1 WM:dwm or xmonad (not working), all: optional programs
#	   $2 all: optional programs

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "Usage: sudo -E env \"PATH=\$PATH\" `basename $0` [all[-wm]] [optional] [hack]"
  exit 0
fi


sudo -u $user mkdir -p "$BACKUPS" "$HOME/.local/bin" "$HOME/Pictures/Screenshots" "$VOLUMES"
rm -rf $HOME/{.zshrc,.zsh_history,.zshenv}
cp ../../../../../../dotfiles/* "$HOME"

. "$HOME/.config/zsh/.zprofile"
user="$SUDO_USER"

#================
# INSTALL OHMYZSH
#================
echo "y" | sudo -u "$user" sh -c "$(sudo -u $user curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp -r $HOME/.config/zsh/{themes,plugins} $HOME/.oh-my-zsh/custom/
case $PKG in
   'eopkg')
      eval "$PKG ur && $PKG up -y" ;;
   'apt')
      eval "$PKG-get update && $PKG-get upgrade" ;;
   'pacman')
      eval "$PKG -Syu" ;;
esac
install_ "git"
awk -i inplace -v user="$user" '/#includedir /etc/sudoers.d/{print; print user " ALL=(ALL) NOPASSWD:ALL";next}1' /etc/sudoers

sudo -u $user git clone https://github.com/Akuseru1/Wiki "$WIKI"
sudo -u $user git clone https://github.com/Akuseru1/suckless-configs "$SUCKLESS"
sudo -u $user git clone https://github.com/Akuseru1/wallpapers "$HOME/Pictures/Wallpapers"


#==================
# INSTALL PACKAGES
#==================
case "$PKG" in
   'eopkg')
      packages=$(awk '{ if (substr($1,1,1) != "#" ) printf "%s ", $0}' packages/eopkg-packages) \
      $PKG_INSTALL -c system.devel ;;
   'apt')
      packages=$(awk '{ if (substr($1,1,1) != "#" ) printf "%s ", $0}' packages/apt-packages) \
      ;;
   'pacman')
      packages=$(awk '{ if (substr($1,1,1) != "#" ) printf "%s ", $0}' packages/pacman-packages) \
      ;;
   *)
      echo 'package manager not found'
      exit
esac

install_ "$packages"

#========================
# INSTALL WINDOW MANAGER
#========================

# xargs is 6 times faster than -exec
find init/* -type f | xargs -n1 -P8 bash

# check latest nvm link
# this is for nvm, otherwise just install npm and do npm install -g neovim
sudo -u $user curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | zsh
. "$XDG_DATA_HOME/nvm/nvm.sh"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | zsh
nvm install node

#======================================================
# BUILD SUCKLESS PROGRAMS AND PROGS NOT IN REPOSITORIES
#======================================================
find build/main/* | xargs -n1 -P3 bash

#================
# BUILD PROGRAMS
#================

custom_wm=0
while [ $# -gt 0 ]; do
   case $1 in
      'optional' | 'all')
         shift
         find build/optional/* | xargs -n1 -P8 bash ;;
      'hack' | 'all')
         shift
         find build/hack/* | xargs -n1 -P8 bash ;;
      'xmonad' | 'all-wm')
         shift
         [ "$1" == 'xmonad' ]\
            && custom_wm=1
         WM/xmonad
         DM/setupXmonad
      *)
         shift
         echo "invalid flag" ;;
   esac
done

# default wm
if [[ $custom_wm == 0 ]]; then
   WM/dwm
   DM/setupDwm
fi

# fixes npm bug
chown -R 1000:1000 "$HOME/.npm"
nvim -c 'PlugInstall'

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# so it uses docker without sudo
usermod -a -G docker $user

# logout and login
# systemctl restart display-manager
