#!/bin/sh

### PROCESS
# mnemonic: [K]ill [P]rocess
# show output of "ps -ef", use [tab] to select one or multiple entries
# press [enter] to kill selected processes and go back to the process list.
# or press [escape] to go back to the process list. Press [escape] twice to exit completely.

if [ -z "$1" ]; then
  pid=$(ps -ef | sed 1d | eval "fzf ${FZF_DEFAULT_OPTS} --preview= -m --header='[kill:process]'" | awk '{print $2}')
else
  pid=$(ps -ef | sed 1d | eval "dmenu -l 30 -p '[kill:process]'" | awk '{print $2}')
fi
shift
if [ "x$pid" != "x" ]; then
  echo $pid | xargs kill -${1:-9}
  kp
fi

