version: "2"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=midata
    volumes:
        - $VOLUMES/mysql:/src/
