#!/bin/sh

if [ -z $1 ]; then
    link=$(xsel -b -o)
    format=$(./showFormats $link a | cut -d" " -f1)
    setsid st -e "$AUTOMATION/ncmpcppStart"
    ncmpcpp $(youtube-dl --prefer-insecure -f${format} -g  $link)
else
    link=$1
    format=$(./showFormats $link a | cut -d" " -f1)
    setsid st -e "$AUTOMATION/ncmpcppStart"
    ncmpcpp $(youtube-dl --prefer-insecure -f${format} -g  $link)
fi

