#!/bin/sh
: > lastRan
prog=$(dmenu -p "Table of Contents for:" </dev/null)
[ -z "$prog" ] && exit
echo "$prog" > lastRan
awk '/\.(S|s)(H|h)/{if ($2) {print $0} else {getline; print toupper($0)}  }' "$(man -w "$prog")" | sed -E 's/\.(SH|sH|Sh|sh)\s//; s/\"//g' | nl -w2 -s " "
# man -k "$prog" | grep "^$prog.*" | awk '{printf " %s %s\n", $1,$2}'
# man -k "$prog" | awk -v var="$prog" "/^$prog/{print}"
# man -k "$prog" | awk -v var="^$prog" ' $0 ~ var {printf "%-4s ",$1; printf "%-4s", $2; printf "%s ","-"; for(i=4;i<=NF;i++){printf "%s ", $i}; printf "\n"}'


