#!/bin/bash
# argumentos son video.mp4 y audio.mp4 asi:

    # ./moddlemix video.mp4 audio.mp4


fname=$(basename -- "$2")
filename_no_ext=${fname%.*}

Mp4ToMp3 "$2"
mix "$1" "$filename_no_ext.mp3"

rm "$filename_no_ext.mp3" "$1" "$2"

