#!/bin/bash
#$1 is the file with the mimes (only first column)
mimeChecker $1 | awk '{print $1}' > convert_log
while read -r line
do
    fname=$(basename -- "$line")
    extension="${fname##*.}"
    filename_no_ext=${fname%.*}
    convert "$line" "$(dirname "$line")/$filename_no_ext.jpg"
done < convert_log
rm convert_log
