#!/bin/sh
font=$(echo "Monospace-10:normal")
if [ $# -eq 1 ]; # if 1 argument, then ask for vid, if 2 show options and return the id
then
    echo "-----------------------------------------" | dmenu -l 20 -b -fn $font
else
    echo "$1" > something
    res=$(echo "$1" | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"\
        | awk '{$0}' \
        | dmenu -l 20 -b -fn $font -p "Results")
    choice=$(echo $res | awk '{print $1}')
    echo $choice
fi
