#!/bin/bash
# $1 is the csv
# $2 is the image folder
path=$(pwd)
count=0
for file in $2/*.jpg; do
    name=$(basename "$file")
    count=$(( count + 1 ))
    if [[ -z $(grep $name $1) ]]; then
        echo empty
        echo "$count"
        exit
    fi
done
shouldBe=$(ls "$2" | wc -l )
if [[ "$count" == $shouldBe ]]; then
    echo OK
else 
    echo Failed
    echo "count: $count"
fi

