#!/bin/bash

path=$(pwd)
count=1
for file in $1/*
do
    filename=$(basename -- "$file")
    extension="${filename##*.}"
    if [[ $extension != "jpg" ]]; then
        echo "failed: $filename"
        exit 
    fi
done < $1
echo "OK"
