#!/bin/sh

# $1 -> empty , get highlight or clipboard
# $1 -> anything, dmenu

if [ ! -z "$1" ]; then
    word=$(dmenu -p "search in dictionary")
else
    word=$(xclip -out -selection primary)
    if [ -z "$word" ]; then
        word=$(xclip -out -selection clipboard)
    else
        printf "%s" "$word" | xclip -selection clipboard
    fi
fi

if [ -z "$word" ]; then
    exit
fi
num_characters=$(echo "$word" | wc -m)
if [ "$num_characters" -gt 2 ]; then
    lines=$(echo "$word" | sed 's/./\0\n/g' )
    word=$(echo "$lines" | dmenu -p "choose the kanji")
fi

firefox https://kanji.koohii.com/study/kanji/$word
rtkSearch "$word"
