#!/bin/sh
mkdir -p "$PROGRAMS/station"
cd "$PROGRAMS/station"
version=$(wget -q -O - "https://dl.getstation.com/download/" | grep "path" | cut -d ' ' -f 2)
wget "https://dl.getstation.com/download/${version}"
