#!/bin/bash

if [ ! -d ".venv" ]; then
    echo "create? (default: y)"
    read ans
    if [[ "$ans" =~ y ]] || [[ "$ans" == "" ]]; then
        python3 -m venv .venv
        source .venv/bin/activate
    fi
else
    source .venv/bin/activate
fi
