#!/bin/bash
#change to dash
updateCheck() {
    var=$(sudo eopkg ur)
    packages="$(sudo eopkg lu | wc -l)更新"
    if [[ $packages == "1更新" ]]; then
        # packages=""
        printf ""
    else
        printf "| %s" "$packages"
    fi
}
declare -A days
days[Mon]="月"
days[Tue]="火"
days[Wed]="水"
days[Thu]="木"
days[Fri]="金"
days[Sat]="土"
days[Sun]="日"

while true; do
    time=$(date +'%H:%M')
    day=$(date +'%a')
    date=$(date +"%d日%m月%y年 (${days[${day}]})")

    battery="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{print $2}' | tr -d "%")電"
    charging=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | cut -d: -f2 | tr -d " ")
    if [[ $battery =~ ^[0-9]電 ]] && [[ $charging != "charging" ]]; then dunstify "Low Battery"; fi


    volume="$(amixer sget Master | awk -F"[][]" '/\[[0-9]/{ print $2 }' | sed 1q | tr -d "%")音"

    [[ -z "$packages" ]] && packages=$(updateCheck) || packages=""

    #wifi connected
    # [[ $(nmcli d status | sed -n '2p' | cut -d" " -f 9) == "connected" ]] && internet=🍥 ||internet=🐡

	xsetroot -name "${packages} | ${volume} | ${battery} | ${time} | ${date}"
	# xsetroot -name "| ${internet} | ${packages} | ${volume} | ${battery} | ${time} | ${date}"
	sleep 1m
done
