#!/bin/bash
#change to dash
checked=""
while true; do
    time=$(date +'%H:%M')
    battery="🔋$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{print $2}' | tr -d "%")"
    if [[ $battery =~ ^[0-9]🔋 ]]; then
        dunstify "Low Battery"
    fi
    volume="🔉$(amixer sget Master | awk -F"[][]" '/\[[0-9]/{ print $2 }' | sed 1q | tr -d "%")"
    if [[ -z "$checked" ]]; then
        checked="true" 
        packages="📦$(sudo eopkg lu | wc -l)"
        if [[ $packages == "📦1" ]]; then
            packages=""
        fi
        date=$(date +'%d/%m/%y')
    fi
	xsetroot -name " ${packages} | ${volume} | ${battery} | ${time} | ${date}"
	sleep 60
done
