#!/bin/bash
#change to dash
while true; do
    time=$(date +'%H:%M')
    # battery="🔋$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{print $2}' | tr -d "%")"
    battery="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{print $2}' | tr -d "%")電"
    if [[ $battery =~ ^[0-9]電 ]]; then
        dunstify "Low Battery"
    fi
    # volume="🔉$(amixer sget Master | awk -F"[][]" '/\[[0-9]/{ print $2 }' | sed 1q | tr -d "%")"
    volume="$(amixer sget Master | awk -F"[][]" '/\[[0-9]/{ print $2 }' | sed 1q | tr -d "%")音"
    if [[ -z "$checked" ]]; then
        checked="true" 
        sudo eopkg ur
        packages="📦$(sudo eopkg lu | wc -l)"
        if [[ $packages == "📦1" ]]; then
            packages=""
        fi

        declare -A days
        days[Mon]="月"
        days[Tue]="火"
        days[Wed]="水"
        days[Thu]="木"
        days[Fri]="金"
        days[Sat]="土"
        days[Sun]="日"
        day=$(date +'%a')
        date=$(date +"%d日%m月%y年 (${days[${day}]})")
    fi
	xsetroot -name " ${packages} | ${volume} | ${battery} | ${time} | ${date}"
	sleep 60
done
