#!/bin/bash


if [[ -z $1 ]]; then
    read -r fullfile
else
    fullfile=$1
fi
if [[ -z $fullfile ]]; then
    echo failed
    exit
fi

fname=$(basename -- "$fullfile")
extension="${fname##*.}"
filename_no_ext=${fname%.*}
