#!/bin/sh

eopkg -y install ghc haskell-cabal-install ghc-devel libx11-devel libxrandr-devel libxscrnsaver-devel libxinerama-devel
cabal update
cabal install xmonad xmonad-contrib

# binaries show up in $HOME/.cabal/bin

xmonad --recompile # works now!


#dependencies xmobar-git
#sudo eopkg -y install alsa-lib-devel libxpm-devel

cabal install xmobar
