#!/bin/bash

today=$( date +%d%m%Y )   # or: printf -v today '%(%Y%m%d)T' -1
number=0

fname=${today}.png
while [[ -e "$HOME/Pictures/screenshots/$fname" ]]; do
    printf -v fname '%s_%02d.png' "$today" "$(( ++number ))"
done
if [[ -z $(pgrep copyq) ]]; then
    copyq &
fi
import -display :1 -window root "$HOME/Pictures/screenshots/${fname}"
copyq write image/png - <  "$HOME/Pictures/screenshots/${fname}" && copyq select 0
dunstify "screenshot taken 🚵"
# for something like pdf
#copyq write application/pdf - < file.pdf && copyq select 0
