  version: '2'

  services:
    drupal:
      image: drupal
      volumes:
        - drupal-modules:/var/www/html/modules
        - drupal-profiles:/var/www/html/profiles
        - drupal-sites:/var/www/html/sites
        - drupal-themes:/var/www/html/themes
      ports:
          - "8080:80"
      depends_on:
          - db
    db:
      image: postgres:latest
      environment:
          - POSTGRES_DB=drupal
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=pass
      volumes:
          - db-data:/var/lib/postgresql/data
  volumes:
      db-data:
      drupal-modules:
      drupal-themes:
      drupal-sites:
      drupal-profiles:
