#!/bin/sh

# git clone --depth=1 https://git.suckless.org/dwm
rm -r dwm
cp -r dwmOriginal dwm
cd dwm
wget -qO- "https://raw.githubusercontent.com/bakkeby/patches/master/dwm/dwm-floatpos-6.2.diff" > floatpos-6.2.diff
wget -qO- "https://dwm.suckless.org/patches/pertag/dwm-pertag-perseltag-6.2.diff" > pertag-perseltag-6.2.diff
wget -qO- "https://dwm.suckless.org/patches/xresources/dwm-xresources-6.2.diff" > xresources-6.2.diff
wget -qO- "https://dwm.suckless.org/patches/alpha/dwm-fixborders-6.2.diff" > fixborders.diff
wget -qO- "https://dwm.suckless.org/patches/scratchpads/dwm-scratchpads-20200414-728d397b.diff" > scratchpads.diff
wget -qO- "https://dwm.suckless.org/patches/swallow/dwm-swallow-20200807-b2de9b0.diff" > swallow.diff
wget -qO- "https://dwm.suckless.org/patches/stacker/dwm-stacker-6.2.diff" > stacker.diff
# wget -qO- "https://dwm.suckless.org/patches/actualfullscreen/dwm-actualfullscreen-20191112-cb3f58a.diff" > fullscreen.diff
wget -qO- "https://raw.githubusercontent.com/bakkeby/patches/master/dwm/dwm-fullscreen-compilation-6.2.diff" > fullscreen.diff
wget -qO- "https://github.com/bakkeby/patches/blob/master/dwm/dwm-fullscreen-compilation-tagswapmon-6.2.diff" > tagswapmon.diff
wget -qO- "https://dwm.suckless.org/patches/hide_vacant_tags/dwm-hide_vacant_tags-6.2.diff" > hide_vacant_tags.diff
wget -qO- "https://dwm.suckless.org/patches/noborder/dwm-noborderfloatingfix-6.2.diff" > noborderfloatingfix.diff
wget -qO- "https://github.com/bakkeby/patches/blob/master/dwm/dwm-vanitygaps-6.2.diff" > vanitygaps.diff

#0,/PATTERN/
# once it finds the pattern and runs the operation, it stops searching and prints the rest

patch --merge < floatpos-6.2.diff
sed -i '0,/<<<\+$/{/<<<\+$/d}' dwm.c
sed -i '0,/>>>\+$/{/>>>\+$/d}' dwm.c
sed -i '0,/===\+$/{/===\+$/d}' dwm.c

patch --merge < pertag-perseltag-6.2.diff
sed -i '0,/<<<\+$/{/<<<\+$/d}' dwm.c
sed -i '0,/>>>\+$/{/>>>\+$/d}' dwm.c
sed -i '0,/===\+$/{/===\+$/d}' dwm.c

patch --merge < xresources-6.2.diff
sed -i '0,/<<<\+$/{/<<<\+$/d}' config.def.h
sed -i '0,/===\+$/{/===\+$/{N;N;N;N;N;d}}' config.def.h


patch --merge < scratchpads.diff
sed -i '0,/<<<\+$/{/<<<\+$/{N;N;N;N;d}}' config.def.h
sed -i '/>>>\+$/{/>>>\+$/d}' config.def.h
sed -i '0,/<<<\+$/{/<<<\+$/{N;d}}' config.def.h
sed -i '/>>>\+$/{/>>>\+$/d}' config.def.h

patch --merge < swallow.diff
sed -i '0,/<<<\+$/{/<<<\+$/d}' dwm.c
sed -i '0,/===\+$/{/===\+$/d}' dwm.c
sed -i '0,/>>>\+$/{/>>>\+$/d}' dwm.c
sed -i '0,/<<<\+$/{/<<<\+$/{N;N;N;N;N;N;N;d}};' config.def.h
sed -i '0,/>>>\+$/{/>>>\+$/d}' config.def.h

patch --merge < stacker.diff
patch --merge < hide_vacant_tags.diff
patch --merge < fullscreen.diff
sed -i '0,/<<<\+$/{/<<<\+$/d}' dwm.c
sed -i '0,/^===*$/{/^===*$/{N;d}};' dwm.c
sed -i '0,/>>>\+$/{/>>>\+$/d}' dwm.c
sed -i '0,/<<<\+$/{/<<<\+$/d}' dwm.c
sed -i '0,/^===*$/{/^===*$/d};' dwm.c
sed -i '0,/>>>\+$/{/>>>\+$/d}' dwm.c

patch --merge < tagswapmon.diff
patch --merge < fixborders.diff

# to check
# patch --merge < noborderfloatingfix.diff
# patch --merge < vanitygaps.diff
make
# make install
