#!/bin/bash
# madrid='Europe/Madrid'
# bogota='Bogota/Colombia'

sudo timedatectl set-ntp 1
if [ -n  "$1" ]; then
    sudo timedatectl set-timezone $1
    exit
fi
echo "choose an option"
options=('Europe/Madrid' 'America/Bogota')
select opt in "${options[@]}"
do
    case $opt in
        'Europe/Madrid')
            sudo timedatectl set-timezone "$opt"
            ;;
        'America/Bogota')
            sudo timedatectl set-timezone "$opt"
            ;;
        *) echo "invalid option";;
    esac
done
