#!/bin/bash
xdotool click 3
xdotool key --delay 10 Up
xdotool key --delay 10 Up
xdotool key --delay 10 Up
xdotool key --delay 10 Up
xdotool key --delay 10 Up
xdotool key --delay 10 Up
xdotool key --delay 10 Up
xdotool key --delay 10 Up
# xdotool key Up
xdotool key Return
# sleep 0.1
xdotool search --name Save key Return
xdotool key Return
xdotool key Return
