#!/bin/bash

failed=0
for file in $1/*; do
    mime_type=$(file --mime-type $file | cut -d" " -f 2 | cut -d"/" -f 2)
    if [[ $mime_type != "jpeg" ]]; then
        echo "$file is $mime_type"
        failed=1
    fi
done

[[ "$failed" == 0 ]] && echo "OK"
