#!/bin/bash

file_name=".projections.json"
folder=$FILES/projections

files=$(find $folder -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
file=$(echo "$files" | fzf --height=75% --preview="[[ ! -f $folder/{}/$file_name ]] && echo '\"{}\" has sub-directories' || (bat --color always $folder/{}/$file_name)" --preview-window="90%:rounded:wrap")
[ -z "$file" ]  && exit

path="$folder/$file"
while [[ ! -f "$path/$file_name" ]]; do
    files=$(find $path -maxdepth 1 -type d -exec basename {} \; | tail -n +2)
    file=$(echo $files | fzf --height=75% --preview="bat --color always $path/{}/$file_name" --preview-window="90%:rounded:wrap")
    if [[ -z $file ]]; then
        exit
    fi
    path="$path/$file"
done

[[ -f "$path/$file_name"  ]] \
    &&  cp "$path/$file_name" . \
    || cp "$folder/$file/$file_name" .
