#!/bin/sh
today=$( date +%d-%m-%Y )   # or: printf -v today '%(%Y%m%d)T' -1
number=0

fname=${today}.png

while [[ -e "$HOME/Pictures/screenshots/$fname" ]]; do
    printf -v fname '%s-%02d.png' "$today" "$(( ++number ))"
done
import -window root ~/Pictures/screenshots/${fname}
