#!/bin/bash
#https://developers.zamzar.com/docs#section-Start_a_conversion_job

function createPdf {
    id_=$(curl -s https://sandbox.zamzar.com/v1/jobs \
    -u 65432af777a957a9a009d0a592703b03745edfa4: \
    -X POST \
    -F "source_file=@${1}" \
    -F "target_format=pdf" | jq '.id')
    
# file="$1"
# path=$(pwd)
# id_=$(curl -s https://sandbox.zamzar.com/v1/jobs \
# -u 65432af777a957a9a009d0a592703b03745edfa4: \
# -X POST \
# -F "source_file=@${path}/${file}" \
# -F "target_format=pdf" | jq '.id')

    echo "job: $id_"
    
    value=$(curl -s https://sandbox.zamzar.com/v1/jobs/${id_} \
        -u 65432af777a957a9a009d0a592703b03745edfa4:) 
    
    status=$(echo "$value" | jq .'status')
    # echo "Segundo: $value"
    echo "status: $status"
    
    while [ "$status" = "\"initialising\"" ] || [ "$status" = "\"converting\"" ]; do
        sleep 3
        value=$(curl -s https://sandbox.zamzar.com/v1/jobs/${id_} \
            -u 65432af777a957a9a009d0a592703b03745edfa4:) 
        status=$(echo "$value" | jq .'status')
    done
    
    echo "Came out: $status"
    
    if [ "$status" != "\"successful\"" ]; then exit; fi
    
    files_to_download=$(echo "$value" | jq .'target_files')
    echo "Files: $files_to_download"
    all_id_of_files_to_download=$(echo "$files_to_download" | jq .'[]'.'id')
    echo "Quinto: ${all_id_of_files_to_download[*]}"
    for idDownload in "${all_id_of_files_to_download[@]}"; do
        curl -s "https://sandbox.zamzar.com/v1/files/${idDownload}/content" \
        -u 65432af777a957a9a009d0a592703b03745edfa4: \
        -L \
        -O \
        -J && dunstify "Converted to pdf"
     done
}




path=$(pwd)
for file_ in "$@"; do
    file_="${path}/${file_}"
    createPdf "$file_"
done

