#!/bin/sh
if [ ! -z "$1" ]; then
    wal -i "$1"
fi
walFolder="$HOME/.cache/wal/colors-wal-dwm.h"
sleep 2
borderColor="#770000"
fgColor="#eeeeee"
sed -E -i "s/sel_border.*\"#.+\";/sel_border[] = \""$borderColor"\";/g" "$walFolder" 
sed -E -i "s/sel_fg.*\"#.+\";/sel_fg[] = \""$fgColor"\";/g" "$walFolder" 

cd "$SUCKLESS/dmenu-4.9"
sudo make clean
sudo make  install
cd "$SUCKLESS/dwm-6.2"
sudo make clean
# sleep 5
sudo make install
dunstify "Changed Wallpaper Successfully 😄"
#😄😄😄😄😄😄😄😄😄😄


