version: "3.5"

# docker pull mongo-express
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ${VOLUMES}/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_PASS}


  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_URL:mongodb://root:example@mongo:27017/
