#!/bin/sh
url=$(dragon -t -x)

#if [ -n "$url" ]; then
#    printf "File Name: "
#    name=""
#    while [ -z $name ] || [ -e $name ]
#    do
#        read -r name
#        if [ -e "$name" ]; then
#            printf "File already exists, overwrite (y|n): "
#            read -r ans
#
#            if [ "$ans" = "y" ]; then
#                break
#            else
#                printf "File Name: "
#            fi
#        fi
#    done
#
    # Download the file with curl
 #   [ -n "$name" ] && curl -o "$name" "$url" || exit 1
     curl -O  "$url" || exit 1
