#+TITLE: Linux

-[[file:~/Documents/wiki/wiki.org][index]]

* Fonts
** libxft bgra
https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/1
put them in .local/share/fonts
do fc-list to check if they are there and finally do
fc-cache to reload

https://www.reddit.com/r/suckless/comments/euwhff/libxft_add_support_for_bgra_glyphs_and_scaling/


git clone https://gitlab.freedesktop.org/xorg/lib/libxft.git
cd libxft
wget -qO- 'https://gitlab.freedesktop.org/xorg/lib/libxft/merge_requests/1.patch' | patch -p1
./autogen.sh
./configure --prefix=/usr --sysconfdir=/etc --disable-static
make
make install
** font folder
    + fc-list
    + fc-cache
* Format USB
df and find partition of usb you want to format
sudo umount /dev/sdb1 or the one you have
sudo mkfs.vfat -n 'TV' -I /dev/sdb1
* Multi-Boot
- Use refind boot manager
  its well automated and it accepts themes
- also you need to mount the boot partition in /boot/efi
  for every OS you install, this worked on Solus/Void/Arch
* Keyboard
** logitech k400 

cant make it have colemak in login, unless you login with the normal keyboard first

Touch tap

Press the Fn key and the left mouse button to toggle between touch tap disable and enabled.

You can also press the left mouse click button at the top-left of the keyboard to perform a click or comfortable two-handed navigation.

You can also tap the touchpad surface to perform a click.

Scrolling

Scroll with two fingers, up or down.

You can also press the Fn key and slide one finger anywhere on the touchpad simultaneously to scroll for comfortable two-handed navigation.
Receiver storage
When you are not using K400 Plus, store the Receiver in the battery compartment so that you never lose it.

use xinput to find your device, in my case
    MatchProduct    "Logitech K400 Plus"
** external keyboard and layout
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "latam"
        Option "XkbModel" "pc104"
        Option "XkbVariant" "colemak"
        Option "XkbOptions" "caps:escape"
EndSection
Section "InputClass"
    Identifier      "Logitech K400r"
    MatchProduct    "Logitech K400 Plus"
    Option "XkbLayout" "latam"
    Option "XkbVariant" "colemak"
    Option "XkbOptions" "caps:escape"
    Option "Emulate3Buttons" "yes"
EndSection

* Arch
** install
follow videos
ON PACSTRAP /mnt linux
or it wont load the kernel!!!
** Hardware
*** Mouse

 put this in a file named /etc/X11/xorg.conf.d/30-touchpad.conf

Section "InputClass"
	Identifier "mytouchpad"
	driver "libinput"
	option "Tapping" "on"
	option "Clickmethod" "clickfinger"
	EndSection

*** Keyboard-Layout

 put this in a file named /etc/X11/xorg.conf.d/00-keyboard.conf 

Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "latam"
        Option "XkbModel" "pc104"
        Option "XkbVariant" "colemak"
        Option "XkbOptions" "caps:escape"
EndSection

in order to have multiple keyboards you need to make sure you make a script
you run when you connect it,

this script would go more or less like this

**** setxkbmap -layout latam, us -model pc104 -options caps:super, grp:win_space_toggle

also , always search for individual configuration for the respective keyboard

my logitech k400 had an utility called solaar which let you switch the fn state

could have saved many hours

*** External-keyboard-Settings
use solaar for logitech
for deactivating the on state for the fn keys
solaar config 1 fn-swap False
*** Keyboard-codes
xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
** Software
*** Pacman
**** lock_database
failed to synchronise (locked database error)
do this

rm /var/lib/pacman/db.lck
*** [[file:Apps.org::Emacs][Emacs]]
**** Dictionaries
Must install from 

sudo pacman -S aspell-es; sudo pacman -S aspell-en
[[file:Semestre_5.org][uni]]
[[file:Apps.org][appi]]
[[file:Apps.org][appi]]
[[file:Apps.org][appi]]
[[file:Apps.org][appi]]  
* Solus
** Hardware
*** Mouse
doing the same as arch, freezes keyboard and mouse, the fix is to do the following
put in .xprofile the following line: 
    synclient TapButton1=1
    synclient TapButton2=3
    synclient TapButton3=2
    
or add the following to: /usr/share/X11/xorg.conf.d/50-synaptics.conf


this is the first input class of the file    

    Section "InputClass"
        Identifier "touchpad catchall"
        Driver "synaptics"
        MatchIsTouchpad "on"
        >>>>>>>>>>>>>>>>>>>>>>>
	      Option "TapButton1" "1"
	      Option "TapButton2" "3"
	      Option "TapButton3" "2"
	      Option "VertTwoFingerScroll" "1"
	      Option "HorizTwoFingerScroll" "1"
        <<<<<<<<<<<<<<<<<<<<<<<<
# This option is recommend on all Linux systems using evdev, but cannot be
# enabled by default. See the following link for details:
# http://who-t.blogspot.com/2010/11/how-to-ignore-configuration-errors.html
#       MatchDevicePath "/dev/input/event*"
EndSection

*** layout colemak 
**** install colemak in solus

https://github.com/nhermosilla14/latam-colemak

**** enable it
then put this in /etc/X11/xorg.conf.d/00-keyboard.conf

Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "latam"
        Option "XkbModel" "pc104"
        Option "XkbVariant" "colemak"
        Option "XkbOptions" "caps:escape"
EndSection
**** make it work in loginscreen
localectl set-x11-keymap latam pc104 colemak

** sudo eopkg up failure 
sudo usysconf run -f ssl-certs
** scripts
most stuff is already done in scripts
** Source .xprofile and .profile by default in lightdm
edit /usr/bin/lightdm-wrapper and source the others
#!/bin/bash

source /usr/share/defaults/etc/profile
source $HOME/.profile
source $HOME/.xprofile

exec $*

** make nvim default EDITOR in ranger and globally
edit the root/.zshrc and /usr/share/defaults/etc/profile
add 
    export EDITOR=nvim
    export VISUAL=nvim
** install dwm
do it normally, then create an .xinitrc
like this: 
    exec mate-session
    #exec dwm
    
if it doesnt work right away check for this:
for error xauth: file /home/user/.serverauth.143
   https://www.linuxquestions.org/questions/slackware-14/xauth-file-home-user-serverauth-1436-does-not-exist-4175576123/
you can delete all .Xauthority* files and the .serverauth.143 file
*** lightdm
also run the script for setupDwm 
** Install Packages
sudo eopkg install
sudo eopkg search
** Backup MATE
dconf dump /org/mate/ > ~/.config/dconf-mate-backup
** Load MATE
dconf load / < dconf-full-backup
** media keybindings
in dconf-editor 
org/mate/settings-daemon/plugins/media-keys
** make xinitrc work
creating xinitrc in $HOME didnt work
editing /etc/X11/xinit/xinitrc didnt work
using solus start up doesnt work with env variables
* Tile Window Managers
** I3
+ i3 size 
  width 1950
  height 1100
** DWM
* [[file:~/org/wiki/Semestre5/Semestre_5.org][Universidad]]

* Japanese
Install fcitx, fcitx-mozc, fcitx-configtool mozc fcitx-gtk3 fcitx-qt5
then logout and login again

change input layout of japanese to colemak
Go to mozc configuration and make sure is in romaji
go to fcitx config and global make sure input key  is super + space

* bash
** show errors in scripts
# at the beggining
set -e

err_report() {
    echo "Error on line $1"
}

trap 'err_report $LINENO' ERR

