#+Title: WIKI CONTENTS
# <s for code block
* [[file:linux.org][Linux]]
* [[file:apps.org][Apps]]
* [[file:technologies.org][Technologies]]
* Classes
to put video courses from shared to your own drive, simply select the videos, and drag and drop them where you want them WHILE holding ctrl or shift + z
** 2020-1
*** Financiera
TN = tasa nominal, tasa de interes mas usada
IP = interes periodico, se calcula del TN dividiendolo por el numero de cuotas (trimestral, semestral etc)
TEA = tasa efectiva anual, es calculable 
**** usura
limite de tea que se puede tener legalmente en colombia por una compra en prestamo
** 2020-2
*** work
**** Modbus
protocol for data transfer for connecting industrial electronic devices (is open source)
Modbus supports communication to and from multiple devices connected to the same cable or Ethernet network. 
For example, a device that measures temperature and a different device to measure humidity, both of which communicates the measurements to a computer. 
*** RTU (Remote Terminal Unit)
electronic device that interfaces physical world objects to a control system (SCADA)
*** TCP (Transmission Control Protocol)
TCP is connection-oriented, and a connection between client and server is established before data can be sent.
 The server must be listening (passive open) for connection requests from clients before a connection is established.
*** UDP
like TCP but is connectionless, meaning that it sacrifices reliability to gain time (more time efficient, less secure)
* Life
** [[file:plans.org][Plans]]
** Dermapen
set to 1.5ml of biotin and 4 dutasteride capsules

+ machine must be set to 1 .

* Windows
** recovery
hetman partition recovery (for hdd recovery)
recuva
* places to eat
 costilla de adam
 + muy poco saludable
   costilla a la plancha
* Done
[x] create line runners for the other algorithms
[x] create a place for the step by step, that is not the monitor
[x] reset printer on clean button
[x] fix bug when changing algorithms
[x] make return work
[x] make errors enter error list
[x] make errors appear in monitor
[x] ~~make program stop running after error, and reset memory if start again after error
[x] Quantummmm
[x] multithread
* small TODO
[] fix statistics
[] finish thread management
[] do Conclusions
[] hacer resumen
 
* Japanese
** n
- yukiyoshi mamizu = young son
- aiue oka
- Fueta kishi
- engawa suguru = ane gyaru
- diisuke = urami
- kakao
- pochi
- meme50
** unit 6
speakers pronounce it nanka which is informal and casual, often used between friends and people of an equal status.
Unit 6
Particles
When speaking English with non-native speakers, you can usually guess their fluency by their familiarity with idiomatic expressions.
For example, when someone says, "John is engaged with Beth" instead of "engaged to" you can guess that the person is not a native
speaker of English. The same is true of the Japanese language. There are many one-syllable words or particles that you need to be able
to use properly in order to convey your ideas accurately to the listener. wa, ga, de, ni, mo, ka, no, and to are some examples of these
particles. wa is often used to indicate that the preceding words are the main topic of a sentence: for example, watashi
wa nihonjin desu. ga is often used the same way, as in, nihongo ga jozu desu. de indicates a place, as in anata no tokoro
de. ni is equivalent to the English "at" when accompanied by a word indicating time, as in ni ji ni, "at two o'clock." mo is "also," as
in anata mo - "you too." ka is put at the end of a sentence to make it a question. no is possessive, as in anata no nihongo (your
Japanese). to is approximately equivalent to "with" in English, as in anato to tabetai desu - "(1) want to eat with you." Though they
may he confusing at times, learning to use these particles properly will greatly contribute to your fluency in Japanese.
** unit 7 o
Cognates and "Borrowed English Loan Words"
No language is free from words borrowed from other languages, and Japanese is no exception. Many English words have been adopted
in Japanese, although the Japanese often pronounce them so differently that English speakers can hardly recognize that they were
originally English. resutoran and biiru illustrate this point. You need to pronounce these and other words with English origins as the
Japanese do, so that you can make yourself understood.
Often, the Japanese have changed not only the pronunciation, but also the form and meanings of these originally English words.
Japanese speakers often prefer to shorten or abbreviate loan words: for example, waapuro for "word processor," pasokon for "personal
computer," and terebi for "television." There are as well some English words used in Japanese whose meanings have changed to a
greater or lesser extent. For example, there are many apartment complexes that are called "mansions" in Japan, usually referring to
condominiums. You may find a pair of socks marked "free size," which really means "one size fits all." In a restaurant, you may be
served mikkusu sando, or "mixed sandwiches." "Mixed" in this context means "assorted," and you will find various
kinds of sandwiches on one plate.
** unit 8
*** Counters
**** Hon
Long things (bottles)
**** mai 
flat materials (paper, plates)
**** dai 
machinery (computers, cars, phones)
**** ken 
for houses and shops
**** nin 
for people
hitori one,
futari two people >> only for people
three people san nin
** unit 11 
masen ka
** unit 12 
How about: 'wa' at the end
isn't: 'ne' at the end
