#!/bin/sh

cd "$PROGRAMS"
eopkg it -y libxkbfile-devel libsecret-devel
sudo -u "$SUDO_USER" git clone https://github.com/microsoft/vscode
cd vscode
sudo -u "$SUDO_USER" yarn
sudo -u "$SUDO_USER" yarn run gulp vscode-linux-x64

ln -s "$PROGRAMS/VSCode-linux-x64/bin/code-oss" "$HOME/.local/bin/code"

sed -i 's/^}$//g' "$PROGRAMS/VSCode-linux-x64/resources/app/product.json"

echo \
"
,
    \"extensionsGallery\": {
    \"serviceUrl\": \"https://marketplace.visualstudio.com/_apis/public/gallery\",
    \"cacheUrl\": \"https://vscode.blob.core.windows.net/gallery/index\",
    \"itemUrl\": \"https://marketplace.visualstudio.com/items\"
    }
}" >> "$PROGRAMS/VSCode-linux-x64/resources/app/product.json"
