version: "3.3"
services:
  staruml:
    image: jamesmstone/staruml
    environment:
    - DISPLAY=$DISPLAY
    volumes:
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/sudoers.d:/etc/sudoers.d:ro
    - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /starUML
