#!/bin/sh
memoryAvailiable=$(df -H | awk '/sd[b-z][0-9]/{print $4}' | awk '/[0-9]/{print $1}')
sudo umount -l "/mnt" && notify-send "unmounted" "memory availiable: $memoryAvailiable" || notify-send "nothing to unmount"

