#!/bin/bash
# Config locations
folders="$XDG_CONFIG_HOME/shortcuts/sf"
dotfiles="$XDG_CONFIG_HOME/shortcuts/sd"

# Output locations
shell_shortcuts="$XDG_CONFIG_HOME/zsh/.aliases"
ranger_shortcuts="$XDG_CONFIG_HOME/ranger/shortcuts.conf"

shellrc="$XDG_CONFIG_HOME/zsh/.zshrc"

#[[ ! -f $folders ]] && curl https://raw.githubusercontent.com/LukeSmithxyz/shortcut-sync/master/folders > "$folders"
#[[ ! -f $dotfiles ]] && curl https://raw.githubusercontent.com/LukeSmithxyz/shortcut-sync/master/configs > "$dotfiles"

# Remove
rm -f "$shell_shortcuts" "$ranger_shortcuts"

#source them if not sourced
(grep "source $shell_shortcuts"  $shellrc)>/dev/null || echo "source $shell_shortcuts" >> $shellrc
(grep "source $HOME/.config/ranger/shortcuts.conf" $HOME/.config/ranger/rc.conf)>/dev/null || echo "source $HOME/.config/ranger/shortcuts.conf" >> $HOME/.config/ranger/rc.conf

# directory shortcuts
sed "/^#/d; /^$/d" $folders | tee >(awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "alias "$1"='\''cd "shortcut" && ls -a'\''"}' >> $shell_shortcuts) \
    >(envsubst | awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut" "$i; else shortcut=$i}; {print "map g"$1" cd "shortcut"\nmap t"$1" tab_new "shortcut"\nmap m"$1" shell mv -v %s "shortcut"\nmap Y"$1" shell cp -rv %s "shortcut}' >> $ranger_shortcuts) >/dev/null
# envsubst changes $HOME -> /home/myuser

# dotfile shortcuts

sed "/^#/d; /^$/d" $dotfiles |tee >(awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "alias "$1"=\"$EDITOR "shortcut"\""}' >> $shell_shortcuts) \
    >(envsubst | awk '{shortcut=""; for ( i = 2; i <= NF; i++ ) if (shortcut != "") shortcut =shortcut"\\ "$i; else shortcut=$i}; {print "map "$1" shell $EDITOR "shortcut}' >> $ranger_shortcuts) >/dev/null
