#!/bin/sh
if [[ -z $1 ]]; then
    read -r fullfile
else
    fullfile=$1
fi
if [[ -z $fullfile ]]; then
    echo failed
    exit
fi
# delete spaces at end of line
fullfile=$(echo $fullfile | sed 's/\s*$//' )

filename=$(basename -- "$fullfile")
extension="${filename##*.}"

case $extension in
    pdf)
        zathura "$fullfile";;

    mp4 | mkv)
        mpv "$fullfile";;

    png | jpg)
        sxiv "$fullfile";;

    *)
        firefox $(cat "$fullfile") 2>/dev/null;;
esac
