#!/bin/bash
# Config locations
folders="$HOME/.config/shortcuts/sf"
dotfiles="$HOME/.config/shortcuts/sd"

# Output locations
shell_shortcuts="$HOME/.aliases"
ranger_shortcuts="$HOME/.config/ranger/shortcuts.conf"

shellrc="$HOME/.zshrc"

#[[ ! -f $folders ]] && curl https://raw.githubusercontent.com/LukeSmithxyz/shortcut-sync/master/folders > "$folders"
#[[ ! -f $dotfiles ]] && curl https://raw.githubusercontent.com/LukeSmithxyz/shortcut-sync/master/configs > "$dotfiles"

# Remove
rm -f $shell_shortcuts $ranger_shortcuts

#source them if not sourced
(grep "source ~/.aliases"  $shellrc)>/dev/null || echo "source ~/.aliases" >> $shellrc
(grep "source $HOME/.config/ranger/shortcuts.conf" $HOME/.config/ranger/rc.conf)>/dev/null || echo "source $HOME/.config/ranger/shortcuts.conf" >> $HOME/.config/ranger/rc.conf

# directory shortcuts
sed "/^#/d; /^$/d" $folders | tee >(awk '{print "alias "$1"=\"cd "$2" && ls -a\""}' >> $shell_shortcuts) \
    >(awk '{print "map g"$1" cd "$2"\nmap t"$1" tab_new "$2"\nmap m"$1" shell mv -v %s "$2"\nmap Y"$1" shell cp -rv %s "$2}' >> $ranger_shortcuts) >/dev/null

# dotfile shortcuts
sed "/^#/d; /^$/d" $dotfiles |tee >(awk '{print "alias "$1"=\"$EDITOR "$2"\""}' >> $shell_shortcuts) \
    >(awk '{print "map "$1" shell $EDITOR "$2}' >> $ranger_shortcuts) >/dev/null
