#!/bin/sh

transparency_min="90"
cd "$XDG_CONFIG_HOME/picom" || exit
match="$(grep -E "\"[0-9]{2}[0-9]?:class_g = 'St'\"];$" picom.conf)"
current_trans=$(echo "$match" | cut -d: -f1 | tr -d '"')
if [ "$current_trans" = $transparency_min ]; then
    sed -E -i "s/\"[0-9]{2}[0-9]?:class_g = 'St'\"];$/\"100:class_g = 'St'\"];/g" picom.conf
else
    sed -E -i "s/\"[0-9]{2}[0-9]?:class_g = 'St'\"];$/\"90:class_g = 'St'\"];/g" picom.conf
fi
