#!/bin/bash

dotrepo=$(cat $XDG_CONFIG_HOME/zsh/.aliases | rg 'dotfiles' | rg -- '--git-dir' | cut -d\" -f2)
path="$1"

filename=${path##*/}
filename=${filename#*.}
file="$path/$filename"
[ -z $path ] \
    && path="$HOME/.local/share/.pass" \
    && file="$path/pass"
zip -r "$file" $path/*
mv "$file.zip" "$file"
eval "$dotrepo secret add $file"
eval "$dotrepo secret hide"
eval "$dotrepo add $file.scr"
rm "$file"
