#!/bin/bash

dotrepo=$(cat $XDG_CONFIG_HOME/zsh/.aliases | rg 'dotfiles' | rg -- '--git-dir' | cut -d\" -f2)
files=$(eval "$dotrepo secret list")

for file in $files; do
    rm "$HOME/$file.scr"
done
