#!/bin/bash

dotrepo=$(cat $XDG_CONFIG_HOME/zsh/.zsh_plugin_aliases | rg 'dotfiles' | rg -- '--git-dir' | cut -d\" -f2)
file="$1"
[ -z $file ] \
    && echo "choose a file to hide" \
    && exit
eval "$dotrepo secret add $file"
eval "$dotrepo secret hide"
eval "$dotrepo add $file.scr"
