#!/bin/bash
#change to dash
while true; do
    battery="🔋$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{print $2}' | tr -d "%")"
    if [[ $battery =~ ^[0-9]🔋 ]]; then
        dunstify "Low Battery"
    fi
    volume="🔉$(amixer sget Master | awk -F"[][]" '/\[[0-9]/{ print $2 }' | sed 1q | tr -d "%")"
	xsetroot -name " ${volume} | ${battery} | $(date +'%H:%M') | $(date +'%d/%m/%y')"
	sleep 60
done
