#!/bin/sh
while true; do
    battery=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{print $2}')
    if [[ $battery =~ '[0-5]%' ]]; then
        dunstify "Low Battery"
    fi
    volume=$(amixer sget Master | awk -F"[][]" '/\[/{ print $2 }' | sed 1q)
	xsetroot -name " ${volume} | ${battery} | $(date +'%H:%M') | $(date +'%d/%m/%y')"
	sleep 60
done
