#!/bin/bash
today=$( date +%Y%m%d )   # or: printf -v today '%(%Y%m%d)T' -1
number=0

fname=${today}.png

while [[ -e "$HOME/Pictures/Screenshots/$fname" ]]; do
    printf -v fname '%s-%02d.png' "$today" "$(( ++number ))"
done

if [[ -z $(pgrep copyq) ]]; then
    copyq &
fi
import "$HOME/Pictures/Screenshots/${fname}"
copyq write image/png - <  "$HOME/Pictures/Screenshots/${fname}" && copyq select 0
dunstify "Screenshot taken 🚵"
# xclip -selection clipboard -target image/png -i ~/Pictures/screenshots/${fname}
