#!/bin/sh
mkdir "$BACKUPS"
mkdir "$PROGRAMS"

# install packages
packages=$(awk '{printf "%s ", $0}' packages)
eopkg -y $packages

#install window manager
if [ "$1" == "dwm" ]; then
   WM/dwm
   DisplayManager/setupDwm
fi

if [ "$1" == "xmonad" ]; then
   WM/xmonad
   DisplayManager/setupXmonad
fi

# fix keyboard and mouse
find init/* -exec {} \;

# build suckless programs and progs not in repositories
find Build-Programs/* -exec {} \;

cp "$XDG_CONFIG_HOME/nvim/init_root.vim" "/root/.config/nvim/init.vim"

cp "$XDG_CONFIG_HOME/ranger/rc_root.conf" "/root/.config/ranger/rc.conf"
cp "$XDG_CONFIG_HOME/ranger/rifle.conf" "/root/.config/ranger/rifle.conf"
cp "$XDG_CONFIG_HOME/ranger/scope.sh" "/root/.config/ranger/scope.sh"

sudo su -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
sudo ln -s "$HOME/.zshrc" "/root"
# this is so the the env variables work
mkdir -p "/root/.local/bin"
sudo ln -s "$HOME/.zprofile" "/root"
sudo ln -s "$HOME/.aliases" "/root"
sudo ln -s "$SCRIPTS" "/root/.local/share/myScripts"
sudo ln -s "$PROGRAMS" "/root/.local/Programs"

mkdir -p "/root/.config/ranger"
mkdir -p "/root/.config/nvim"
cp "$XDG_CONFIG_HOME/nvim/init_root.vim" "/root/.config/nvim"
cp "$XDG_CONFIG_HOME/ranger/rc_root.conf" "/root/.config/ranger/rc.conf"
cp "$XDG_CONFIG_HOME/completion_fzf.zsh" "/root/.config/completion_fzf.zsh"
cp "$XDG_CONFIG_HOME/zshPlugAlias" "/root/.config/zshPlugAlias"
cp "$XDG_CONFIG_HOME/colemak-less" "/root/.config/colemak-less"
