#!/bin/sh

#args: $1 WM:dwm or xmonad, all: optional programs
#	   $2 all: optional programs

user="kanon"
# add access to sudoers
awk -i inplace -v user="$user" '/#includedir /etc/sudoers.d/{print; print user " ALL=(ALL) NOPASSWD:ALL";next}1' /etc/sudoers

sudo -u $user git clone https://github.com/Akuseru1/Wiki "$HOME/.local/share/wiki"


source "$HOME/.zprofile"
sudo -u $user mkdir "$BACKUPS" "$HOME/.local/bin"

# install packages
packages=$(awk '{ if (substr($1,1,1) != "#" ) printf "%s ", $0}' packages)
eopkg install -y -c system.devel
eopkg install -y $packages

#install window manager

if [ "$1" == "dwm" ]; then
   WM/dwm
   DM/setupDwm
fi

if [ "$1" == "xmonad" ]; then
   WM/xmonad
   DM/setupXmonad
fi

# fix keyboard and mouse
find init/* -exec {} $user \;

# check latest nvm link
# this is for nvm, otherwise just install npm and do npm install -g neovim
sudo -u $user curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | zsh
source "$HOME/.config/nvm/nvm.sh"
nvm install node

# build suckless programs and progs not in repositories
find Build-Programs/* -exec {} $user \;

# optional progs
if [ "$1" == "all" ] || [ "$2" == "all" ]; then
   find optional-programs/* -exec {} $user \;;

fi

# vim-plug
cd "$HOME/.config/nvim"
sudo -u $user sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
# fixes npm bug
chown -R 1000:1000 "$HOME/.npm"
nvim -c 'PlugInstall'

sudo -u "$user" sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"



# logout and login
