#!/bin/sh

#args: $1 WM:dwm or xmonad, all: optional programs
#	   $2 all: optional programs

user="$SUDO_USER"
# add access to sudoers
awk -i inplace -v user="$user" '/#includedir /etc/sudoers.d/{print; print user " ALL=(ALL) NOPASSWD:ALL";next}1' /etc/sudoers

sudo -u $user git clone https://github.com/Akuseru1/Wiki "$HOME/.local/share/wiki"


source "$HOME/.zprofile"

sudo -u $user mkdir -p "$BACKUPS" "$HOME/.local/bin" "$HOME/Pictures/Screenshots" "$HOME/Master/Data/docker/volumes"

# install packages
packages=$(awk '{ if (substr($1,1,1) != "#" ) printf "%s ", $0}' packages)
eopkg install -y -c system.devel
eopkg install -y $packages

#install window manager

if [ "$1" == "dwm" ]; then
   WM/dwm
   DM/setupDwm
fi

if [ "$1" == "xmonad" ]; then
   WM/xmonad
   DM/setupXmonad
fi

find init/* -type f -exec {} \;

# check latest nvm link
# this is for nvm, otherwise just install npm and do npm install -g neovim
sudo -u $user curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | zsh
source "$HOME/.config/nvm/nvm.sh"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | zsh
nvm install node

# build suckless programs and progs not in repositories
find build/* -exec {} \;

# optional progs
if [ "$1" == "all" ] || [ "$2" == "all" ]; then
   find build-optional/* -exec {} \;;

fi

# vim-plug
cd "$HOME/.config/nvim"
sudo -u $user sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
# fixes npm bug
chown -R 1000:1000 "$HOME/.npm"
nvim -c 'PlugInstall'

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# so it uses docker without sudo
usermod -a -G docker $user
sudo -u "$user" sh -c "$(sudo -u \"$user\" curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"



# logout and login
