#!/bin/bash

# the csv has to be in the same folder as all the pictures for this script to work correctly
# the sum of 20% is always more because there can be more than one tag in a single picture
default="\"image\",\"xmin\",\"ymin\",\"xmax\",\"ymax\",\"label\""
[[ ! -e "test" ]] && mkdir "test"
[[ ! -e "training" ]] && mkdir "training" 
echo "$default" > "training/train.csv"

# copy original to new file
csv=$1
path=$(dirname "$csv")
cp "$csv" "test/test.csv"
cp ${path}/*.jpg "test/"
csv="test/test.csv"


# gets 20% of all tags
options=$(tail -n +2 "$csv" | cut -d "," -f 6 | cut -d '"' -f 2 | sort | uniq)
tags_file=$(awk -F "," '{print $6}' "$csv")
declare -A tags
for tag in $options; do
    tags[$tag]=$(printf "%.0f" $(echo "$(grep "$tag" <(echo "$tags_file") | wc -l) * 0.2" | bc)) 
done

#print
printf "%-8s %s %-5s %s %s\n" "LABEL" "|" "TOTAL" "|" "20%"
sumAll=0
for tag in "${!tags[@]}"; do
    sumAll="$(( "$sumAll" + "${tags[$tag]}" ))"
    printf "%-8s %s %-5s %s %s\n" "${tag}:" "|" "$(grep "$tag" <(echo "$tags_file") | wc -l)" "|" "${tags[$tag]}"
done
    printf "_______________________\n"
    printf "%22s\n" "$sumAll"
echo "${tags["Vest"]}"
echo "${tags["Glasses"]}"
echo "${tags["Gloves"]}"
echo "${tags["Helmet"]}"

instancesLeft() 
{
    sum=0
    for test_size in "${tags[@]}"; do
        sum=$(( $sum + test_size ))
    done
    echo "$sum"
}

fixRange()
{
    num=$RANDOM
    numLines=$(( $(cat $csv | wc -l) - 1 ))
    #count digits
    numDigits=$(echo "${#numLines}")
    power=$(( 10 ** $numDigits  ))
    line=$(( $num % $power ))
    while [[ "$line" -gt $numLines || $line == 0 || $line == 1 ]]; do
        num=$RANDOM
        line=$(( $num % $power ))
    done
    echo "$line"
}


# choose random image
iter=0
while [[ $(instancesLeft) -gt 0 ]]; do
    num=$(fixRange)
    # echo "num is: $num"
    image_name=$(sed -n "${num}p" "$csv" | cut -d "," -f 1)
    tags_in_image=$(grep "$image_name" "$csv" | cut -d "," -f 6 | cut -d '"' -f 2 | sort | uniq)
    changed=0
    for tag in $tags_in_image; do
        elementsLeft=${tags[$tag]}
        numOcurrences=$(grep "$image_name" "$csv" | grep "$tag" | cut -d "," -f 6 | wc -l)
        if [[ "$elementsLeft" -le 0 ]]; then
            # echo "continued for: $tag, instancesLeft: $(instancesLeft)"
            # echo "${tags["Vest"]}"
            # echo "${tags["Glasses"]}"
            # echo "${tags["Gloves"]}"
            # echo "${tags["Helmet"]}"
            continue
        fi
        changed=1
        unset tags[$tag]
        tags[$tag]=$(( $elementsLeft - $numOcurrences ))
        grep "$image_name" "$csv" | grep "$tag" >> "training/train.csv"
        iter=$(( iter + 1 ))
    done
    if [[ "$changed" == 1 ]]; then
        sed -i "/$image_name/d" "$csv"
        image_path=$(echo "$image_name" | cut -d '"' -f 2 )
        mv "test/$image_path" "training/"
    fi
done
