#!/bin/sh
wal -i "$1"
walFolder="$HOME/.cache/wal/colors-wal-dwm.h"
sleep 2
borderColor="#770000"
fgColor="#eeeeee"
sed -E -i "s/sel_border.*\"#.+\";/sel_border[] = \""$borderColor"\";/g" "$walFolder" 
sed -E -i "s/sel_fg.*\"#.+\";/sel_fg[] = \""$fgColor"\";/g" "$walFolder" 
cd "$HOME/Documents/Suckless/dwm-6.2"
sudo make clean
sudo make install
cd "$HOME/Documents/Suckless/dmenu-4.9"
sudo make clean
sudo make  install
dunstify "Changed Wallpaper Successfully 😄"
#😄😄😄😄😄😄😄😄😄😄


