#!/bin/sh

#dependencies for dwm
eopkg install -y libxft-devel libxinerama-devel
cd "$SUCKLESS/dwm-6.2"
currentUser=$(grep "$USER" config.h)
if [ -z "$currentUser" ]; then
    sed -i "s|#include \"/home/.*|#include \"$HOME/.cache/wal/colors-wal-dwm.h\"|g" config.h
fi
make clean
make
make install
