#!/bin/sh
drivePlusSize=$(lsblk | awk '/sd[b-z][0-9]/{print $1 ,$4}' |tr -d "└─" |  dmenu -p "escoja el drive")
drive=$(echo "$drivePlusSize" | awk '{print$1}')

if [ -z "$drive" ]; then
    notify-send "failed to mount"
    exit
fi
size=$(echo "$drivePlusSize" | awk '{print$2}')
sudo mount "/dev/$drive" /mnt && notify-send "mounted drive: $size"
memoryAvailiable=$(df -H | awk '/sd[b-z][0-9]/{print $4}' | awk '/[0-9]/{print $1}')
notify-send "memory availiable: ${memoryAvailiable}"
