#!/bin/sh


# cut from end to beggining change the -f7 to the number you need
temp=$BOOKS
temp2=$BOOKS
first=1

# list_folders_containing_pdf=$(find "$BOOKS" -type f -name '*.pdf' -exec sh -c 'for d; do dirname "$d"; done ' sh {} + | uniq -u)
while [[ -d $temp2 ]]; do
    #need to change so it only shows directories with pdf inside
    pathdirs=$(ls -d ${temp2}/*/ 2>/dev/null)
    pathfiles=$(find "$temp2" -name  '*.pdf')
    if [[ ! -z pathdirs ]]; then
        all=$(echo "${pathdirs} 
            ${pathfiles}")
        else
            all=${pathfiles}
    fi
    temp2=${temp}/$(echo $(echo "$all"  | cut -d'/' -f7- | dmenu -l 15 ) | sed 's/\/$//' 2>/dev/null)

    # if chose nothing
    if [[ $temp2 == ${temp}/ ]]; then
        exit
    fi
done
[[ ! -z $temp2 ]] && $AUTOMATION/open_with "$temp2" || echo failed

