#!/bin/bash

docsets=$(ls $HOME/.local/share/Zeal/Zeal/docsets)
all=""
for doc in $docsets; do
    if [[ $doc == "C++.docset" ]]; then
        all=$(echo "Cpp:;${all}")
        continue
    fi
    doc=$(echo ${doc} | sed -E 's/(_|-).*\././g')
    all="$(echo $doc | sed -r 's/(.+)\..+/\1:/g');${all}"
done
sourceVal=$(echo $all | sed 's/;/\n/g'  | dmenu -i -p "Docs:")

# sourceVal=$( echo \
#     'Cpp:
#     Vim:
#     React:' | dmenu -i
# )
[[ ! -z $sourceVal ]] && zeal "$sourceVal"
