#!/bin/bash
# $1 is the csv
# $2 is the image folder

path=$(pwd)
count=1
while read -r line
do
    name=$(echo "$line" | cut -d, -f 1 | tr -d '"')
    if [[ $name == "filename" ]]; then
        continue
    fi
    count=$(( count + 1 ))
    if [[ -z $(grep "$name" <(ls $2)) ]]; then
         echo "$count"
         echo empty
         exit
    fi
done < $1

echo "$count"


shouldBe=$(cat $1 | wc -l ) 
if [[ "$count" == $shouldBe ]]; then
    echo OK
else 
    echo Failed
    echo "count: $count"
    echo "should be: $shouldBe"
fi

