#!/bin/sh
#https://www.reddit.com/r/suckless/comments/euwhff/libxft_add_support_for_bgra_glyphs_and_scaling/
#dependencies
eopkg it util-macros-devel
cd "$PROGRAMS"   
git clone https://gitlab.freedesktop.org/xorg/lib/libxft.git
cd libxft
wget -qO- 'https://gitlab.freedesktop.org/xorg/lib/libxft/merge_requests/1.patch' | patch -p1
./autogen.sh
./configure --prefix=/usr --sysconfdir=/etc --disable-static
make
make install
