#!/bin/sh


# change input layout of japanese to colemak
# Go to mozc configuration and make sure is in romaji
# go to fcitx config and global make sure input key  is super + space

# for japanese font-droid-ttf


# for japanese (might also need to install fcitx-gtk3 and fcitx-qt5)
sudo eopkg -y install fcitx mozc fcitx-mozc fcitx-configtool 
