#!/bin/sh

#pdfgrep dependencies, download the tar https://pdfgrep.org/download.html
sudo eopkg -y install libgcrypt-devel poppler-devel

cd "$PROGRAMS"
git clone https://gitlab.com/pdfgrep/pdfgrep.git
cd pdfgrep
./configure
sudo make
sudo make install
