#!/bin/sh
[ "$(stat -c %y ~/dev/corona/info > 2/dev/null | cut -d ' ' -f 1)" != "$(date '+%Y-%m-%d')" ] && 
	curl -s https://corona-stats.online\?source\=2 > ~/dev/corona/info

grep -m 3 Colombia ~/dev/corona/info | 
	sed 's/│/;/g; s/ //g; s/║//g ' | 
	awk -F ';' '{print "Infected " ($3) " Deaths " ($5)" Recovered "($4)" Week "($10)}'
