version: "3.9"

services:
    transmission-rss:
    image: nning2/transmission-rss
    ports:
      - 9091:9091
    volumes:
        - ./settings.json:/etc/transmission-daemon/settings.json
        - ./transmission-rss.conf:/etc/transmission-rss.conf

