#!/bin/sh

# install isync
eopkg -y install isync

# install pass
cd "$PROGRAMS"
git clone https://git.zx2c4.com/password-store
cd password-store
make install

#install msmtp

cd "$PROGRAMS"
git clone https://git.marlam.de/git/msmtp.git
cd msmtp
autoreconf -i
./configure; make; make install

# install neomutt
cd "$PROGRAMS"
git clone https://github.com/neomutt/neomutt
cd neomutt
./configure
make
make install

#install mutt wizard

# cd "$PROGRAMS"
# git clone https://github.com/LukeSmithxyz/mutt-wizard
# cd mutt-wizard
# make 
# make install
