#!/bin/zsh

#path=find "$HOME" -name "copy_conf"

cd "$HOME" || exit

path_dot="$(find "$HOME" -name 'dotfiles')"
aliases=$(cat "$path_dot/.config/zsh/.aliases")
plug_aliases=$(cat "$path_dot/.config/zsh/zsh_plugin_aliases")


echo "$aliases
$plug_aliases" >> "$HOME/.zshrc"

cp "$path_dot/.config/nvim/init.vim" "$HOME/.config/nvim/init.vim"

# dont overwrite default
cp "$path_dot/.config/nvim/modules/keybindings.vim" "$HOME/.vimrc_mine"


options=("kali" "solus" "arch")
current=$(grep "^ID=" /etc/os-release | cut -d '=' -f 2 | tr -d '"')

for opt in "${options[@]}"; do
    if $opt == "kali"
        sudo apt install tmux
        exit
    fi

    if $opt == "solus"
        sudo eopkg install tmux
        exit
    fi

    if $opt == "arch"
        sudo eopkg -S tmux
        exit
    fi
end

installers=("eopkg" "apt" "pacman")
select opt in "${installers[@]}"
do
    case $opt in
        'eopkg')
            sudo eopkg install tmux
            ;;
        'apt')
            sudo apt install tmux
            ;;
        'pacman')
            sudo pacman -S tmux
            ;;
        *) echo "invalid option";;
    esac
done
