#!/bin/sh

# drive list -shared | grep -i "$1"
# i: id
# m: mime type
# s: size
# t: time modified
# p: path to file

fullInfo=$(rclone lsf  --format "imstp" --drive-shared-with-me "gdrive:" | column -t -s ";" | sort -k4,5 | tac)
selection=$(echo "$fullInfo" | awk ' $2 == "video/mp4" {for(i=6;i<=NF;i++){printf "%s ", $i}; printf "\n"}' | dmenu -i -l 5 | sed 's/\s*$//g')
if [ -z "$selection" ]; then
    exit
fi
# line_count=$(($(printf "%s\n" "$selection" | wc -l) - 1))
# i=0
# while [ $i -le $line_count ]; do

    # selection=$(printf "%s" "$selection" | awk '{if (NR == 2) print $0}')
    selection=$(echo "${fullInfo}" | grep -i "${selection}" | grep -i "video/mp4")
    id=$(echo "${selection}" | sort -r -k3 | awk '{print $1}' | head -n 1)
    firefox --new-tab "https://drive.google.com/file/d/${id}/view"
    # j=$(( j + 1 ))
# done

