#!/bin/bash


folder_paths=$(find "$CLASSES" -type d -name "libros" -printf "%p\n")
declare -A folders
folder_names=""
# ifs explain https://unix.stackexchange.com/questions/184863/what-is-the-meaning-of-ifs-n-in-bash-scripting
IFS=$'\n'
for path in $folder_paths; do
    folder_name=$(cut -d "/" -f 9 <(echo "$path"))
    folders["$folder_name"]="$path"
    if [[ ! -z "$folder_names" ]]; then
        printf -v folder_names "%s\n%s" $folder_names "$folder_name"
    else
        printf -v folder_names "%s" "$folder_name"
    fi
done

# folder_names=$(cut -d "/" -f 9 <(echo "$folder_paths"))
chosen=$(echo "$folder_names" | dmenu -i -p "choose subject")
book=$(ls "${folders["$chosen"]}" | dmenu -i -p "choose book")

zathura "${folders["$chosen"]}/$book"

