#!/bin/bash

folder_paths=$(find "$CLASSES" -type d -name "libros" -printf "%p\n")
declare -A folders
subject_names=""
# ifs explain https://unix.stackexchange.com/questions/184863/what-is-the-meaning-of-ifs-n-in-bash-scripting
IFS=$'\n'
for path in $folder_paths; do
    folder_name=$(cut -d "/" -f 9 <(echo "$path"))
    folders["$folder_name"]="$path"
    if [[ ! -z "$subject_names" ]]; then
        printf -v subject_names "%s\\n%s" $subject_names "$folder_name"
    else
        printf -v subject_names "%s" "$folder_name"
    fi
done

# subject_names=$(cut -d "/" -f 9 <(echo "$folder_paths"))
chosen=$(echo "$subject_names" | dmenu -i -p "choose subject")
book=$(ls "${folders["$chosen"]}" | dmenu -i -p "choose book")

[[ -z "$book" ]] && exit

extension="${book##*.}"
case "$extension" in
    pdf)
        zathura "${folders["$chosen"]}/$book";;
    epub)
        okular "${folders["$chosen"]}/$book";;
esac

