#!/bin/sh

# task spooler
ts -C
wiki=0
dotfiles=0
cd "$WIKI" || exit
status=$(git status | grep -qF 'working tree clean' || echo "DIRTY")
if [ "$status" = "DIRTY" ]; then
    wiki=0
    git status
    printf "\n\n"
    echo "enter wiki changes"
    read -r message
    if [ ! -z "$message" ]; then
        printf "\n\n"
        git add -u
        printf "\n\n"
        git commit -m "$message"
        ts git push origin master
    fi
fi

alias dotrepo="git --git-dir=${HOME}/Documents/DotFilesRepository/ --work-tree=${HOME}"
cd "$SCRIPTS" || exit
dotrepo diff --exit-code --quiet
status=$(dotrepo status | grep -qF 'nothing to commit (use -u to show untracked files)' || echo "DIRTY")
if [ "$status" = "DIRTY" ]; then
    dotfiles=1
    dotrepo status
    printf "\n"
    echo "enter script changes"
    read -r message
    if [ ! -z "$message" ]; then
        printf "\n\n"
        dotrepo add -u
        printf "\n\n"
        dotrepo commit -m "$message"
        ts dotrepo push origin master
    fi
fi

if [ wiki = 1 ] && [ dotfiles = 1 ]; then
    ts -t 0
    ts -t 1
    exit
fi

if [ wiki = 1 ]; then
    ts -t 0
    exit
fi

if [ dotfiles = 1 ]; then
    ts -t 0
    exit
fi
