#!/bin/sh

alias dotrepo="git --git-dir=${HOME}/Documents/DotFilesRepository/ --work-tree=${HOME}"
cd "$SCRIPTS" || exit
dotrepo diff --exit-code --quiet
status=$(dotrepo status | grep -qF 'working directory clean' || echo "DIRTY")
if [ "$status" = "DIRTY" ]; then
    dotrepo status
    printf "\n"
    echo "enter script changes"
    read -r message
    git add -u
    git add .
    printf "\n\n"
    dotrepo add -u
    dotrepo commit -m "$message"
    dotrepo push origin master
fi

cd "$WIKI" || exit
status=$(git status | grep -qF 'working directory clean' || echo "DIRTY")
if [ "$status" = "DIRTY" ]; then
    git status
    printf "\n\n"
    printf "enter wiki changes"
    read -r message
    git add -u
    printf "\n\n"
    git commit -m "$message"
    git push origin master
fi
