version: "2"

services:
  pbivqnyreg:
    build: .
    image: pbivqnyreg
    volumes:
      - "${WORK}/pbivqnyreg:/usr/src/app"
    command: "sh /usr/src/app/bootstrap"
    # command: "python3 manage.py test qr"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
        - db-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
